name       : httpie
version    : 2.3.0
release    : 11
source     :
    - https://github.com/httpie/httpie/archive/2.3.0.tar.gz : 17c18a67ea57599b75b59c081b57c7d0239eabf5cc7d8de347840a4006f57ee4
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-requests-toolbelt
setup      : |
    %python3_setup
install    : |
    %python3_install
