name       : httpie
version    : 2.1.0
release    : 9
source     :
    - https://github.com/jakubroztocil/httpie/archive/2.1.0.tar.gz : aea482da09341a3d205761d828c7125884c9d0eb77a53cd4d2e6042e4670182b
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-requests
setup      : |
    %python3_setup
install    : |
    %python3_install
