name       : httpie
version    : 1.0.3
release    : 7
source     :
    - https://github.com/jakubroztocil/httpie/archive/1.0.3.tar.gz : ecfb1ecdfd1468100bd9ffecebe1bea6d7d72c72149ea91f3d0112dc8ef03c7a
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive
    UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-requests
setup      : |
    %python3_setup
install    : |
    %python3_install
