name       : httpie
version    : 3.2.2
release    : 16
source     :
    - https://github.com/httpie/httpie/archive/refs/tags/3.2.2.tar.gz : 797fe33afe3bf0a4364a869a7d73f5c728f67d4ac47039be41e08bd564f86bb0
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-defusedxml
    - python-multidict
    - python-requests-toolbelt
    - python-rich
setup      : |
    %python3_setup
install    : |
    %python3_install
