name       : httpie
version    : 0.9.6
release    : 1
source     :
    - https://github.com/jkbrzt/httpie/archive/0.9.6.tar.gz : a70475690e030cc8c627cde158647f305dc3c9a54c2d3c1ed5bab8d4587fd0fc
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-requests
setup      : |
    %python3_setup
install    : |
    %python3_install
