name       : httpie
version    : 1.0.0
release    : 4
source     :
    - https://github.com/jkbrzt/httpie/archive/1.0.0.tar.gz : 2ed14abf146743fc237881ed5658c108a43d965ae9f7dbbd72648ae9daad0c46
license    : BSD-3-Clause
component  : network.clients
summary    : Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
description: |
    Command line HTTP client, a user-friendly curl alternative with an intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-requests
setup      : |
    %python3_setup
install    : |
    %python3_install
